NumPy
It stands for "Numerical Python". NumPy is a Python module that provides fast and efficient array operations of homogeneous data. It is the core library for scientific computing in Python providing a high-performance multidimensional array object, and tools for working with arrays.

In [1]:
#importing a numpy 
import numpy as np

In [2]:
#creating a numpy array
a = np.array([1,2,3])  #1-D array
b = np.array([[2,3,5], [7,8,9]]) #2-D array
print(b)
a

[[2 3 5]
 [7 8 9]]


array([1, 2, 3])

Attributes of numpy array
.shape
.size
.ndim
.itemsize
.dtype

In [3]:
array = np.arange(1,11)
array

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [4]:
dim =array.ndim
dim

1

In [5]:
reshaped = array.reshape(5,2)
new_dim = reshaped.ndim
print(dim)
print(new_dim)


1
2


Creating new numpy array

In [6]:
#empty
np.empty((2,3), dtype = 'int')

array([[0, 0, 0],
       [0, 0, 0]])

In [7]:
#zero
np.zeros((2,), dtype = "float")

array([0., 0.])

In [8]:
array = np.array([[1, 2, 3], [5,6,7], [8,9,10]])

In [9]:
array

array([[ 1,  2,  3],
       [ 5,  6,  7],
       [ 8,  9, 10]])

In [10]:
#indexing

In [11]:
array[1:,1:]

array([[ 6,  7],
       [ 9, 10]])

In [12]:
#eye
np.eye(8)

array([[1., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1.]])

In [13]:
#one
np.ones((2,3), dtype='int')

array([[1, 1, 1],
       [1, 1, 1]])

In [14]:
#full
np.full((2, 2), 8)

array([[8, 8],
       [8, 8]])

In [15]:
#Create an array out a 4x4 identity matrix with dtype float32 and save it in a variable named array
array = np.identity(4, dtype = 'float32')
array

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]], dtype=float32)

Creating with Existing Data
New NumPy arrays can also be created from already existing ones.


In [16]:
#asarray()
a = [1,2,3]
b = np.asarray(a)
b

array([1, 2, 3])

In [17]:
#python tuples
a=((1,2),(3,4))

#convery to NumPy array
b=np.asarray(a)
print(b)

[[1 2]
 [3 4]]


np.fromiter( )
This function creates a NumPy ndarray from an iterable

In [18]:
a=np.fromiter([1,2,3,4],dtype='int8')
b=np.fromiter((1,2,3,4),dtype='int8')
c=np.fromiter(range(1,5),dtype='int8')
d=np.fromiter('string',dtype='S50')

print("Array a is ",a)
print("Array b is ",b)
print("Array c is ",c)
print("Array d is ",d)

Array a is  [1 2 3 4]
Array b is  [1 2 3 4]
Array c is  [1 2 3 4]
Array d is  [b's' b't' b'r' b'i' b'n' b'g']


In [19]:
#Creating new arrays with .arrange and .linspace .logspace
a = np.arange(1,50)
a

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34,
       35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49])

In [20]:
a = np.linspace(1, 10, 500)
a

array([ 1.        ,  1.01803607,  1.03607214,  1.05410822,  1.07214429,
        1.09018036,  1.10821643,  1.12625251,  1.14428858,  1.16232465,
        1.18036072,  1.19839679,  1.21643287,  1.23446894,  1.25250501,
        1.27054108,  1.28857715,  1.30661323,  1.3246493 ,  1.34268537,
        1.36072144,  1.37875752,  1.39679359,  1.41482966,  1.43286573,
        1.4509018 ,  1.46893788,  1.48697395,  1.50501002,  1.52304609,
        1.54108216,  1.55911824,  1.57715431,  1.59519038,  1.61322645,
        1.63126253,  1.6492986 ,  1.66733467,  1.68537074,  1.70340681,
        1.72144289,  1.73947896,  1.75751503,  1.7755511 ,  1.79358717,
        1.81162325,  1.82965932,  1.84769539,  1.86573146,  1.88376754,
        1.90180361,  1.91983968,  1.93787575,  1.95591182,  1.9739479 ,
        1.99198397,  2.01002004,  2.02805611,  2.04609218,  2.06412826,
        2.08216433,  2.1002004 ,  2.11823647,  2.13627255,  2.15430862,
        2.17234469,  2.19038076,  2.20841683,  2.22645291,  2.24

In [21]:
c = np.logspace(1, 5, 70)
c


array([1.00000000e+01, 1.14280206e+01, 1.30599655e+01, 1.49249555e+01,
       1.70562698e+01, 1.94919403e+01, 2.22754295e+01, 2.54564067e+01,
       2.90916341e+01, 3.32459793e+01, 3.79935737e+01, 4.34191342e+01,
       4.96194760e+01, 5.67052394e+01, 6.48028644e+01, 7.40568469e+01,
       8.46323172e+01, 9.67179864e+01, 1.10529514e+02, 1.26313356e+02,
       1.44351164e+02, 1.64964807e+02, 1.88522122e+02, 2.15443469e+02,
       2.46209240e+02, 2.81368427e+02, 3.21548418e+02, 3.67466194e+02,
       4.19941123e+02, 4.79909581e+02, 5.48441658e+02, 6.26760256e+02,
       7.16262912e+02, 8.18546731e+02, 9.35436890e+02, 1.06901920e+03,
       1.22167735e+03, 1.39613539e+03, 1.59550640e+03, 1.82334800e+03,
       2.08372585e+03, 2.38128619e+03, 2.72133877e+03, 3.10995155e+03,
       3.55405904e+03, 4.06158599e+03, 4.64158883e+03, 5.30441728e+03,
       6.06189899e+03, 6.92755066e+03, 7.91681916e+03, 9.04735724e+03,
       1.03393385e+04, 1.18158173e+04, 1.35031404e+04, 1.54314166e+04,
      

In [22]:
v = np.array([[1,2,3,4,5],[6,7,8,9,10]])

In [23]:
v.reshape(5,2)

array([[ 1,  2],
       [ 3,  4],
       [ 5,  6],
       [ 7,  8],
       [ 9, 10]])

Indexing and slicing

In [24]:
#example
a = np.array([[1,2,3],[4,5,6],[7,8,9]])
a

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [25]:
a[2,1]

8

In [26]:
a[:2,:2]

array([[1, 2],
       [4, 5]])

In [27]:
print(a[2,:])

[7 8 9]


In [28]:
#integer indexing
a=np.array([[1,2],[3,4],[5,6]])

print(a[[0,1,2],[0,1,0]])

[1 4 5]


In [29]:
#boolean indexing
a = np.array([[4,7,1],[2,5,7],[7,1,1]])
a

array([[4, 7, 1],
       [2, 5, 7],
       [7, 1, 1]])

In [30]:

mask = a > 3
print(a[mask])

[4 7 5 7 7]


In [31]:
array = np.array([3,4,5,3+5j,0])
array

array([3.+0.j, 4.+0.j, 5.+0.j, 3.+5.j, 0.+0.j])

In [32]:
real = np.isreal(array)
real_array = array[real]

In [33]:
print(real_array)

[3.+0.j 4.+0.j 5.+0.j 0.+0.j]


In [34]:
imag = np.iscomplex(array)

# boolean filter
imag_array = array[imag]
imag_array

array([3.+5.j])

Vectorization
Vectorization is the ability of NumPy by which we can perform operations on entire arrays rather than on a single element. When looping over an array or any data structure in Python, there’s a lot of overhead involved. Vectorized operations in NumPy delegate the looping internally to highly optimized C and Fortran functions, making for a cleaner and faster Python code.

In [35]:
#initializing
a = np.array([[1,2,3],[4,5,6],[7,8,9]])
b=np.array([[10,11,12],[13,14,15],[16,17,18]])

In [36]:
print(a+b)
print('=================')
print(np.add(a,b))

[[11 13 15]
 [17 19 21]
 [23 25 27]]
[[11 13 15]
 [17 19 21]
 [23 25 27]]


In [37]:
print(a-b)
print('=================')
print(np.subtract(a,b))

[[-9 -9 -9]
 [-9 -9 -9]
 [-9 -9 -9]]
[[-9 -9 -9]
 [-9 -9 -9]
 [-9 -9 -9]]


In [38]:
print(a*b)
print('=================')
print(np.multiply(a,b))

[[ 10  22  36]
 [ 52  70  90]
 [112 136 162]]
[[ 10  22  36]
 [ 52  70  90]
 [112 136 162]]


In [39]:
print(a/b)
print('=================')
print(np.divide(a,b))

[[0.1        0.18181818 0.25      ]
 [0.30769231 0.35714286 0.4       ]
 [0.4375     0.47058824 0.5       ]]
[[0.1        0.18181818 0.25      ]
 [0.30769231 0.35714286 0.4       ]
 [0.4375     0.47058824 0.5       ]]


In [40]:
np.sqrt(a)

array([[1.        , 1.41421356, 1.73205081],
       [2.        , 2.23606798, 2.44948974],
       [2.64575131, 2.82842712, 3.        ]])

In [41]:
np.log(a)

array([[0.        , 0.69314718, 1.09861229],
       [1.38629436, 1.60943791, 1.79175947],
       [1.94591015, 2.07944154, 2.19722458]])

In [42]:
#array comparision
c = np.array([1,2,3,4])
d = np.array([1,2,3,4])
print(np.array_equal(c,d))

True


In [43]:
a = np.array([[1,4,9],[16,25,36]])
print(a)
print('=================')
# computes sum over columns
print(a.sum(axis=0))
print('==========')

# computes sum over rows
print(a.sum(axis=1))
print('==========')

# computes total sum
print(a.sum())

[[ 1  4  9]
 [16 25 36]]
[17 29 45]
[14 77]
91


Broadcasting
Have you wondered how this operation np.array([1, 2, 3]) + 4 was successfully carried out? It was all due to the broadcasting power of NumPy arrays

In [44]:
centigrade_temps = np.array([0, 10, 25, 32, 80, 99.99])

Project